//! Symbol data organized by category for the symbol picker.

/// A symbol category with its items
pub struct SymbolCategory {
    pub name: &'static str,
    pub icon: &'static str,
    pub symbols: &'static [(&'static str, &'static str)], // (symbol, description)
}

/// All symbol categories
pub static CATEGORIES: &[SymbolCategory] = &[
    SymbolCategory {
        name: "Math",
        icon: "∑",
        symbols: &[
            ("+", "plus"),
            ("−", "minus"),
            ("×", "multiply"),
            ("÷", "divide"),
            ("=", "equals"),
            ("≠", "not equal"),
            ("≈", "approx equal"),
            ("≡", "identical"),
            ("<", "less than"),
            (">", "greater than"),
            ("≤", "less or equal"),
            ("≥", "greater or equal"),
            ("±", "plus-minus"),
            ("∓", "minus-plus"),
            ("∞", "infinity"),
            ("√", "square root"),
            ("∛", "cube root"),
            ("∑", "summation"),
            ("∏", "product"),
            ("∫", "integral"),
            ("∂", "partial"),
            ("∇", "nabla/del"),
            ("∆", "delta"),
            ("π", "pi"),
            ("θ", "theta"),
            ("α", "alpha"),
            ("β", "beta"),
            ("γ", "gamma"),
            ("δ", "delta"),
            ("ε", "epsilon"),
            ("λ", "lambda"),
            ("μ", "mu"),
            ("σ", "sigma"),
            ("τ", "tau"),
            ("φ", "phi"),
            ("ω", "omega"),
            ("∈", "element of"),
            ("∉", "not element of"),
            ("⊂", "subset"),
            ("⊃", "superset"),
            ("⊆", "subset or equal"),
            ("∪", "union"),
            ("∩", "intersection"),
            ("∅", "empty set"),
            ("∀", "for all"),
            ("∃", "there exists"),
            ("¬", "not"),
            ("∧", "and"),
            ("∨", "or"),
            ("⊕", "xor/direct sum"),
            ("⊗", "tensor product"),
            ("ℝ", "real numbers"),
            ("ℤ", "integers"),
            ("ℕ", "natural numbers"),
            ("ℂ", "complex numbers"),
            ("ℚ", "rationals"),
        ],
    },
    SymbolCategory {
        name: "Currency",
        icon: "$",
        symbols: &[
            ("$", "dollar"),
            ("€", "euro"),
            ("£", "pound"),
            ("¥", "yen/yuan"),
            ("₹", "rupee"),
            ("₽", "ruble"),
            ("₩", "won"),
            ("₿", "bitcoin"),
            ("¢", "cent"),
            ("₺", "lira"),
            ("₴", "hryvnia"),
            ("₦", "naira"),
            ("₱", "peso"),
            ("₫", "dong"),
            ("₸", "tenge"),
            ("₡", "colon"),
            ("₵", "cedi"),
            ("₭", "kip"),
            ("฿", "baht"),
            ("৳", "taka"),
        ],
    },
    SymbolCategory {
        name: "Arrows",
        icon: "→",
        symbols: &[
            ("←", "left"),
            ("→", "right"),
            ("↑", "up"),
            ("↓", "down"),
            ("↔", "left-right"),
            ("↕", "up-down"),
            ("↖", "upper-left"),
            ("↗", "upper-right"),
            ("↘", "lower-right"),
            ("↙", "lower-left"),
            ("⇐", "double left"),
            ("⇒", "double right"),
            ("⇑", "double up"),
            ("⇓", "double down"),
            ("⇔", "double left-right"),
            ("⇕", "double up-down"),
            ("↩", "return left"),
            ("↪", "return right"),
            ("↰", "up then left"),
            ("↱", "up then right"),
            ("↲", "down then left"),
            ("↳", "down then right"),
            ("⟵", "long left"),
            ("⟶", "long right"),
            ("⟷", "long left-right"),
            ("⟹", "long double right"),
            ("⟸", "long double left"),
            ("↺", "counterclockwise"),
            ("↻", "clockwise"),
            ("➜", "heavy right"),
            ("➔", "heavy right 2"),
            ("➤", "right arrowhead"),
        ],
    },
    SymbolCategory {
        name: "Punctuation",
        icon: "…",
        symbols: &[
            ("…", "ellipsis"),
            ("–", "en dash"),
            ("—", "em dash"),
            ("‐", "hyphen"),
            ("'", "left single quote"),
            ("'", "right single quote"),
            ("\u{201c}", "left double quote"),
            ("\u{201d}", "right double quote"),
            ("«", "left guillemet"),
            ("»", "right guillemet"),
            ("‹", "left single guillemet"),
            ("›", "right single guillemet"),
            ("·", "middle dot"),
            ("•", "bullet"),
            ("†", "dagger"),
            ("‡", "double dagger"),
            ("§", "section"),
            ("¶", "paragraph"),
            ("©", "copyright"),
            ("®", "registered"),
            ("™", "trademark"),
            ("°", "degree"),
            ("′", "prime"),
            ("″", "double prime"),
            ("‰", "per mille"),
            ("№", "numero"),
            ("⁂", "asterism"),
            ("※", "reference mark"),
        ],
    },
    SymbolCategory {
        name: "Technical",
        icon: "⌘",
        symbols: &[
            ("⌘", "command"),
            ("⌥", "option/alt"),
            ("⇧", "shift"),
            ("⌃", "control"),
            ("⎋", "escape"),
            ("⏎", "return"),
            ("⌫", "delete"),
            ("⇥", "tab"),
            ("⌨", "keyboard"),
            ("⚙", "gear"),
            ("⚡", "lightning"),
            ("✓", "check"),
            ("✗", "cross"),
            ("✕", "x mark"),
            ("☐", "unchecked box"),
            ("☑", "checked box"),
            ("☒", "x-ed box"),
            ("★", "filled star"),
            ("☆", "empty star"),
            ("♠", "spade"),
            ("♣", "club"),
            ("♥", "heart"),
            ("♦", "diamond"),
            ("♩", "quarter note"),
            ("♪", "eighth note"),
            ("♫", "beamed notes"),
            ("♬", "beamed sixteenths"),
            ("⚐", "white flag"),
            ("⚑", "black flag"),
            ("☰", "hamburger menu"),
            ("⋮", "vertical ellipsis"),
            ("⋯", "horizontal ellipsis"),
        ],
    },
    SymbolCategory {
        name: "Boxes & Lines",
        icon: "┌",
        symbols: &[
            ("┌", "top-left corner"),
            ("┐", "top-right corner"),
            ("└", "bottom-left corner"),
            ("┘", "bottom-right corner"),
            ("─", "horizontal"),
            ("│", "vertical"),
            ("├", "left tee"),
            ("┤", "right tee"),
            ("┬", "top tee"),
            ("┴", "bottom tee"),
            ("┼", "cross"),
            ("╔", "double top-left"),
            ("╗", "double top-right"),
            ("╚", "double bottom-left"),
            ("╝", "double bottom-right"),
            ("═", "double horizontal"),
            ("║", "double vertical"),
            ("╠", "double left tee"),
            ("╣", "double right tee"),
            ("╦", "double top tee"),
            ("╩", "double bottom tee"),
            ("╬", "double cross"),
            ("█", "full block"),
            ("▓", "dark shade"),
            ("▒", "medium shade"),
            ("░", "light shade"),
            ("▀", "upper half"),
            ("▄", "lower half"),
            ("▌", "left half"),
            ("▐", "right half"),
        ],
    },
    SymbolCategory {
        name: "Superscript",
        icon: "²",
        symbols: &[
            ("⁰", "superscript 0"),
            ("¹", "superscript 1"),
            ("²", "superscript 2"),
            ("³", "superscript 3"),
            ("⁴", "superscript 4"),
            ("⁵", "superscript 5"),
            ("⁶", "superscript 6"),
            ("⁷", "superscript 7"),
            ("⁸", "superscript 8"),
            ("⁹", "superscript 9"),
            ("⁺", "superscript plus"),
            ("⁻", "superscript minus"),
            ("⁼", "superscript equals"),
            ("ⁿ", "superscript n"),
            ("₀", "subscript 0"),
            ("₁", "subscript 1"),
            ("₂", "subscript 2"),
            ("₃", "subscript 3"),
            ("₄", "subscript 4"),
            ("₅", "subscript 5"),
            ("₆", "subscript 6"),
            ("₇", "subscript 7"),
            ("₈", "subscript 8"),
            ("₉", "subscript 9"),
            ("ₐ", "subscript a"),
            ("ₑ", "subscript e"),
            ("ₒ", "subscript o"),
            ("ₓ", "subscript x"),
        ],
    },
];

/// Search symbols by name or description.
pub fn search(query: &str) -> Vec<(&'static str, &'static str)> {
    let q = query.to_lowercase();
    let mut results = Vec::new();

    for cat in CATEGORIES {
        if cat.name.to_lowercase().contains(&q) {
            results.extend_from_slice(cat.symbols);
        } else {
            for &(sym, desc) in cat.symbols {
                if desc.to_lowercase().contains(&q) || sym.contains(query) {
                    results.push((sym, desc));
                }
            }
        }
    }

    results
}
