[package]
name = "author-clipboard-hypr-picker"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
homepage.workspace = true

[[bin]]
name = "author-clipboard-hypr-picker"
path = "src/main.rs"

[dependencies]
author-clipboard-ui-gtk = { path = "../ui-gtk" }
author-clipboard-shared = { path = "../shared" }
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd = "2"

[lints]
workspace = true
